### ISSUE TITLE
LAST_VALUE behaviour is inconsistent to FIRST_VALUE behaviour

### ISSUE THREAD

**Issue by antonior** [MicrosoftDocs/sql-docs.pt-br#20]
Hi all,

I'm either missing something important or I may have found a bug.

Unlike FIRST_VALUE, and all other function that I know of and uses an "Over (partition by columnA order by columnB)" clause, LAST_VALUE function partitionates the data by a combination of "partition by" and "order by" columns, as if the clause were "over (partition by columnA, columnB order by columnB)".

I would expect that the following 2 statements would return the same values:

LAST_VALUE(columnC)  over (partition by columnA order by columnB asc )
FIRST_VALUE(columnC) over (partition by columnA order by columnB desc)

Instead, the following 2 statements return the same values:

LAST_VALUE(columnC)  over (partition by columnA          order by columnB asc)
FIRST_VALUE(columnC) over (partition by columnA, columnB order by columnB desc)

If it's really a bug and it gets fixed, this page's first example ("A. Using LAST_VALUE over partitions") should return different results as the first 5 rows should return "2003-02-05" and the other rows should return "2003-01-12" for LastValue column.

Thanks in advance for whoever may reply this issue!

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 43ffda42-ab8a-74df-0b14-92cc12cf39df
* Version Independent ID: 1fd3836e-52fa-014c-67de-b73e0fd810ed
* Content: [LAST_VALUE (Transact-SQL) - SQL Server](https://docs.microsoft.com/pt-br/sql/t-sql/functions/last-value-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/last-value-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.pt-br/blob/live/docs/t-sql/functions/last-value-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srvbpigh** [comment]
Hello, @antonior
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @antonior

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
