### ISSUE TITLE
Atualizacao para o Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by MarcosVenicioToledo** [MicrosoftDocs/sql-docs.pt-br#22]
Eu acredito que vocês deveriam atualizar o procedimento para o Ubuntu 18.04 LTS, pois essa versão substitui a 16.04 LTS e seguinte exatamente esse procedimento o SQL Server nao funciona.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Introdução ao SQL Server no Ubuntu - SQL Server](https://docs.microsoft.com/pt-br/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-2017#feedback)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs.pt-br/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by srvbpigh** [comment]
Hello, @MarcosVenicioToledo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @MarcosVenicioToledo 

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 
Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/sql-docs/issues/2723

Agradecemos sua contribuição aos nossos artigos. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
