### ISSUE TITLE
Command line to create full database diagram by Sql Server Management Studio or windows console.

### ISSUE THREAD

**Issue by mchomem** [MicrosoftDocs/sql-docs.pt-br#24]
Hello dears,

Its exists this possibility?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a8bc803d-3aee-0e1f-ab64-31c5af48e9f9
* Version Independent ID: 472fcb4b-39c3-72a3-d2af-4eba68b72f04
* Content: [Criar um novo diagrama de banco de dados (Visual Database Tools) - SQL Server](https://docs.microsoft.com/pt-br/sql/ssms/visual-db-tools/create-a-new-database-diagram-visual-database-tools?view=sql-server-2017)
* Content Source: [docs/ssms/visual-db-tools/create-a-new-database-diagram-visual-database-tools.md](https://github.com/MicrosoftDocs/sql-docs.pt-br/blob/live/docs/ssms/visual-db-tools/create-a-new-database-diagram-visual-database-tools.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by srvbpigh** [comment]
Hello, @mchomem
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @mchomem ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
