### ISSUE TITLE
Link quebrado

### ISSUE THREAD

**Issue by vanderHobus** [MicrosoftDocs/sql-docs.pt-br#25]
Link para o download (onde diz: Baixar o SQL Server Management Studio 18.3) está apontando para página inicial: https://www.microsoft.com/pt-br/?ref=go

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Baixar o SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/pt-br/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.pt-br/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by srvbpigh** [comment]
Hello, @vanderHobus
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Phnc** [comment]
O link da página em inglês funciona
[https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017](url)

**Comment by lichasu** [comment]
Olá, @vanderHobus

O link será atualizado automaticamente na próxima rodada de localização.

Obrigado pela sua contribuição.
