### ISSUE TITLE
Pratice Examples

### ISSUE THREAD

**Issue by leoTotvs** [MicrosoftDocs/sql-docs.pt-br#26]
This [page](https://docs.microsoft.com/pt-br/sql/ssms/scripting/search-text-with-regular-expressions?view=sql-server-2017) should contain practices examples, like the most of docs.microsoft pages.

Below is a practical example, so that character matching starts with a letter between a and z, using LIKE or PATINDEX :
DECLARE @STRING AS VARCHAR(100) = 'T1904';

SELECT @STRING AS STRING, CASE WHEN @STRING LIKE '[A-Z]%' THEN 'MATCH' ELSE 'NOT MATCH' END AS TESTING_MATCH_LIKE

SELECT @STRING AS STRING, CASE WHEN patindex('[A-Z]%',@STRING) &gt; 0 THEN 'MATCH' ELSE 'NOT MATCH' END AS TESTING_MATCH_PATINDEX 

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 9027fbf7-358e-f42f-91e3-5dd316bd68a1
* Version Independent ID: 8751863c-1c8f-fe89-11be-e66ebc8416fa
* Content: [Pesquisar texto com expressões regulares - SQL Server](https://docs.microsoft.com/pt-br/sql/ssms/scripting/search-text-with-regular-expressions?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/scripting/search-text-with-regular-expressions.md](https://github.com/MicrosoftDocs/sql-docs.pt-br/blob/live/docs/ssms/scripting/search-text-with-regular-expressions.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by srvbpigh** [comment]
Hello, @leoTotvs
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @leoTotvs 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/3120.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
