### ISSUE TITLE
Incorrect application version and no download links working

### ISSUE THREAD

**Issue by dliedke** [MicrosoftDocs/sql-docs.pt-br#28]
The page is outdated for pt-BR, latest SSMS version should be 18.3.1 and also all download links are still broken.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Baixar o SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/pt-br/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.pt-br/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by srvbpigh** [comment]
Hello, @dliedke
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @dliedke 

Thank you for your feedback. The document is being localized and will be updated soon.

Kind regards,
Microsoft DOCS International Team
