### ISSUE TITLE
Sinal negativo faltando no argumento de bigint

### ISSUE THREAD

**Issue by gmilani** [MicrosoftDocs/sql-docs.pt-br#29]
Na [seção argumentos](https://docs.microsoft.com/pt-br/sql/t-sql/statements/create-sequence-transact-sql?view=sql-server-ver15#arguments) dessa página está faltando o sinal de negativo no intervalo do bigint.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 3ab9d5f8-6808-bc61-11e7-01a1fd5fab74
* Version Independent ID: 1d1d5a01-51aa-e0e8-277e-e7ba0a50ce42
* Content: [CREATE SEQUENCE (Transact-SQL) - SQL Server](https://docs.microsoft.com/pt-br/sql/t-sql/statements/create-sequence-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-sequence-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.pt-br/blob/live/docs/t-sql/statements/create-sequence-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by srvbpigh** [comment]
Hello, @gmilani
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @gmilani

Sua contribuição é muito bem-vinda. Nossa equipe analisou seus comentários e parece que esse problema foi já registrado. 

Verifique o problema https://github.com/MicrosoftDocs/sql-docs.pt-br/pull/30 O problema está duplicado, por isso o fechamos. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
