### ISSUE TITLE
Videoaula

### ISSUE THREAD

**Issue by Rodnei-EliteSQL** [MicrosoftDocs/sql-docs.pt-br#31]
Aqui tem uma videoaula ilustrando a utilização, espero que seja útil. :)

https://elitesql.com.br/funcao-agregacao-avg-sql/

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: e3b44f8a-f567-edb6-173b-69955fc98381
* Version Independent ID: 3779a6ab-4cbd-f912-49e9-1d69b9e2dc39
* Content: [AVG (Transact-SQL) - SQL Server](https://docs.microsoft.com/pt-br/sql/t-sql/functions/avg-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/avg-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.pt-br/blob/live/docs/t-sql/functions/avg-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srvbpigh** [comment]
Hello, @inforodnei
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @Rodnei-EliteSQL 

Seus comentários são muito bem-vindos. Ficamos felizes em ver que sua experiência com nossa documentação atende às suas expectativas. 

Incentivamos você a fornecer seus comentários valiosos para que possamos continuar melhorando sua experiência.

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
