### ISSUE TITLE
Videoaula

### ISSUE THREAD

**Issue by Rodnei-EliteSQL** [MicrosoftDocs/sql-docs.pt-br#32]
Confira a videoaula ilustrando a utilização, espero que seja útil.

https://elitesql.com.br/funcao-de-agregacao-checksum-agg/

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 2d1194e2-bd58-af06-420c-1bea9e25c5a1
* Version Independent ID: f7dd22c2-e34e-f860-3903-c34d43d4b58e
* Content: [CHECKSUM_AGG (Transact-SQL) - SQL Server](https://docs.microsoft.com/pt-br/sql/t-sql/functions/checksum-agg-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/checksum-agg-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.pt-br/blob/live/docs/t-sql/functions/checksum-agg-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srvbpigh** [comment]
Hello, @inforodnei
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @inforodnei

Seus comentários são muito bem-vindos. Ficamos felizes em ver que sua experiência com nossa documentação atende às suas expectativas. 

Incentivamos você a fornecer seus comentários valiosos para que possamos continuar melhorando sua experiência.

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
