### ISSUE TITLE
Utilizando repetição de caracteres não funciona

### ISSUE THREAD

**Issue by BrunoMR** [MicrosoftDocs/sql-docs.pt-br#33]
Tentei utilizar a repetição de caracteres descrita:

Repetir n vezes | ^n
Exemplo: [0-9]^4 e não funciona.

Exemplo aplicado
select
  *
from
  tabela
where
  coluna like '%[0-9]^9%'

Utilizando o comando acima não retornou resultado algum, sendo que a linha tinha informações como estas:
PED. 812899458 * INT. CLAUDIO TAMAGOSHI

**Comment by srvbpigh** [comment]
Hello, @BrunoMR
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @BrunoMR 

Apreciamos muito a sua contribuição. Ainda assim, esses comentários se referem a produtos. Registre sua sugestão usando o botão "Fornecer comentários sobre produtos" na parte inferior da página do DOCS.

Se você tiver qualquer comentário relacionado a documentação, sinta-se livre para registrá-lo por este canal.

Verdadeiramente apreciamos sua contribuição para os nossos artigos.

Equipe internacional do Microsoft DOCS

**Comment by BrunoMR** [comment]
Tudo bem Cecília, irei fazer o que você indicou. Muito obrigado pela sua
atenção.
