### ISSUE TITLE
Broken debian packages repository

### ISSUE THREAD

**Issue by rodrigomaraujo** [MicrosoftDocs/sql-docs.pt-br#34]
Since Dez, 13 2019 update the package repository is bronken.

https://packages.microsoft.com/debian/10/prod/dists/buster/Release and https://packages.microsoft.com/debian/10/prod/dists/buster/InRelease has different size and hashes from https://packages.microsoft.com/debian/10/prod/dists/buster/main/binary-amd64/Packages.bz2

Release (right values):
MD5Sum:
 232d6c5b746913f648a6445998206f6f    18556 main/binary-amd64/Packages.bz2

InRelease (wrong values):
MD5Sum:
 4153a12e4a5629bfb14ed98f4c8ac234   156065 main/binary-amd64/Packages.bz2

Now we can't  install ODBC Driver in Debian Linux systems.

APT error:

E: Failed to fetch https://packages.microsoft.com/debian/10/prod/dists/buster/main/binary-amd64/Packages.bz2  File has unexpected size (18556 != 156065). Mirror sync in progress? [IP: 40.76.35.62 443]
   Hashes of expected file:
    - Filesize:156065 [weak]
    - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
    - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
    - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
    - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
   Release file created at: Thu, 12 Dec 2019 19:59:19 +0000

**Comment by srvbpigh** [comment]
Hello, @rodrigomaraujo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @rodrigomaraujo, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/3803. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
