### ISSUE TITLE
Opinião

### ISSUE THREAD

**Issue by emanoellucasml** [MicrosoftDocs/sql-docs.pt-br#37]
Muito bom!

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 4468b4c6-2aaa-c98c-250e-5eb2f7a94f5d
* Version Independent ID: 21fd3da5-22ea-531f-081c-4b6ba17787b6
* Content: [Pesquisa com curinga (%) - SQL Server](https://docs.microsoft.com/pt-br/sql/t-sql/language-elements/percent-character-wildcard-character-s-to-match-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/language-elements/percent-character-wildcard-character-s-to-match-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.pt-br/blob/live/docs/t-sql/language-elements/percent-character-wildcard-character-s-to-match-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by srvbpigh** [comment]
Hello, @emanoellucasml
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @emanoellucasml 

Seus comentários são muito bem-vindos. Ficamos felizes em ver que sua experiência com nossa documentação atende às suas expectativas.

Incentivamos você a fornecer seus comentários valiosos para que possamos continuar melhorando sua experiência. 

Atenciosamente,

Equipe Internacional do Microsoft DOCS
